name: trek_gen
description: A sample command-line application.
version: 1.0.0
repository: 

environment:
  sdk: ^3.5.0-47.0.dev

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
